# Generated by Django 5.1.7 on 2025-03-24 22:09

import datetime
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, default=0)),
                ('description', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('could_use_in_bouquet', models.BooleanField(default=True, null=True)),
                ('wiki_page', models.URLField(default='https://www.wikipedia.org/', null=True, unique_for_date='delivered_at')),
                ('name', models.CharField(blank=True, max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_email', models.EmailField(max_length=254, null=True)),
                ('name', models.CharField(max_length=64, null=True)),
                ('invoice', models.FileField(null=True, upload_to='')),
                ('user_uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('discount_size', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fresh_period', models.DurationField(default=datetime.timedelta(days=5), help_text='Use this field if you need to have information about fresh time', null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.FloatField(default=1.0, null=True)),
                ('flowers', models.ManyToManyField(to='lesson_5.flower', verbose_name='Flowers in bouquet')),
            ],
            managers=[
                ('shop', django.db.models.manager.Manager()),
            ],
        ),
    ]
